version: '3.9'

services:
  app:
    image: dd000697/my_model:latest
    ports:
      - "8000:8000"
    environment:
      - HOST=${HOST}
      - DATABASE=${DATABASE}
      - DBUSERNAME=${DBUSERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - .:/app
    command: sh run_app.sh [DEVICE]