name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Build Docker image
      run: |
        # Add debugging to ensure requirements.txt is present
        echo "Listing files in api directory:"
        ls -la api/
        docker build -t my_model:latest -f api/Dockerfile .

    - name: Tag Docker image
      run: |
        docker tag my_model:latest dd000697/my_model:latest

    - name: Log in to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        docker push dd000697/my_model:latest

    - name: Debug Working Directory
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing files:"
        ls -la

    - name: Deploy
      run: |
        cd api
        bash run_ci_cd.sh

    - name: Run Docker Compose
      run: |
        cd api
        docker-compose up -d
